VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "XmlTest2"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Implements XMLObject

Public Property Get Shape() As String
End Property
Public Property Let Shape(ByVal val As String)
End Property

Public Property Get XmlObject_Color() As String
End Property
Public Property Let XmlObject_Color(ByVal val As String)
End Property

Public Property Get XmlObject_Length() As Integer
End Property
Public Property Let XmlObject_Length(ByVal val As Integer)
End Property



