VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "XMLObject"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Property Get Color() As String
End Property
Public Property Let Color(ByVal val As String)
End Property

Public Property Get Length() As Integer
End Property
Public Property Let Length(ByVal val As Integer)
End Property

