VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "XmlTest3"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'Option Explicit
'Implements XmlTest2
'
'
'Private mColor As String
'Private mLength As Integer
'Private mShape As String
'
'Public Property Get XmlTest2_Shape() As String
'    XmlTest2_Shape = mShape
'End Property
'Public Property Let XmlTest2_Shape(ByVal val As String)
'    mShape = val
'End Property
'
'Public Property Get XmlTest2_XmlObject_Color() As String
'    XmlObject_Color = mColor
'End Property
'Public Property Let XmlTest2_XmlObject_Color(ByVal val As String)
'    mColor = "purple"
'End Property
'
'Public Property Get XmlTest2_XmlObject_Length() As Integer
'    XmlObject_Length = mLength
'End Property
'Public Property Let XmlTest2_XmlObject_Length(ByVal val As Integer)
'    XmlObject_mLength = 5
'End Property


